// GENERATED BY AMBORAS — do not edit manually
// Generated: 2026-07-24T04:03:01.263Z
// Class A plugins: none

import type { PluginRegistry } from '../../types/plugins'

export const PLUGIN_REGISTRY: PluginRegistry = {
  head: [],
  bodyEnd: [],
  rootProviders: [],
  homeHero: [],
  homeBelowFeatured: [],
  pdpAfterTitle: [],
  pdpBeforePrice: [],
  pdpBelowAddToCart: [],
  pdpTrustSignals: [],
  pdpAfterDescription: [],
  pdpTab: [],
  pdpAnalytics: [],
  collectionAboveGrid: [],
  collectionCard: [],
  collectionBelowGrid: [],
  cartDrawerFooter: [],
  cartUpdate: [],
  checkoutOrderSummary: [],
  checkoutStart: [],
  checkoutComplete: [],
  searchAboveResults: [],
  accountOverview: [],
  account: [],
  authSignup: [],
}